import colors from '../styles/colors';

export default [
  {
    month: 'Jan',
    portfolio: 105,
    portfolioColor: colors.purple[900],
    dollar: 67,
    dollarColor: colors.blue[50],
    etf: 175,
    etfColor: colors.red[900],
  },
  {
    month: 'Fev',
    portfolio: 150,
    portfolioColor: colors.purple[900],
    dollar: 119,
    dollarColor: colors.blue[50],
    etf: 122,
    etfColor: colors.red[900],
  },
  {
    month: 'Mar',
    portfolio: 73,
    portfolioColor: colors.purple[900],
    dollar: 177,
    dollarColor: colors.blue[50],
    etf: 63,
    etfColor: colors.red[900],
  },
  {
    month: 'Apr',
    portfolio: 61,
    portfolioColor: colors.purple[900],
    dollar: 53,
    dollarColor: colors.blue[50],
    etf: 122,
    etfColor: colors.red[900],
  },
  {
    month: 'May',
    portfolio: 188,
    portfolioColor: colors.purple[900],
    dollar: 41,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Jun',
    portfolio: 105,
    portfolioColor: colors.purple[900],
    dollar: 80,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Jul',
    portfolio: 188,
    portfolioColor: colors.purple[900],
    dollar: 100,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Aug',
    portfolio: 215,
    portfolioColor: colors.purple[900],
    dollar: 100,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Sep',
    portfolio: 109,
    portfolioColor: colors.purple[900],
    dollar: 60,
    dollarColor: colors.blue[50],
    etf: 80,
    etfColor: colors.red[900],
  },
  {
    month: 'Oct',
    portfolio: 188,
    portfolioColor: colors.purple[900],
    dollar: 41,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Nov',
    portfolio: 200,
    portfolioColor: colors.purple[900],
    dollar: 75,
    dollarColor: colors.blue[50],
    etf: 198,
    etfColor: colors.red[900],
  },
  {
    month: 'Dez',
    portfolio: 260,
    portfolioColor: colors.purple[900],
    dollar: 90,
    dollarColor: colors.blue[50],
    etf: 140,
    etfColor: colors.red[900],
  },
];
