import colors from '../styles/colors';

export default [
  {
    month: 'Jan',
    capitalGain: 105,
    capitalGainColor: colors.purple[900],
    dividends: 67,
    dividendsColor: colors.blue[50],
    currencyGain: 175,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Fev',
    capitalGain: 190,
    capitalGainColor: colors.purple[900],
    dividends: 119,
    dividendsColor: colors.blue[50],
    currencyGain: 122,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Mar',
    capitalGain: 73,
    capitalGainColor: colors.purple[900],
    dividends: 177,
    dividendsColor: colors.blue[50],
    currencyGain: 63,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Apr',
    capitalGain: 61,
    capitalGainColor: colors.purple[900],
    dividends: 53,
    dividendsColor: colors.blue[50],
    currencyGain: 122,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'May',
    capitalGain: 188,
    capitalGainColor: colors.purple[900],
    dividends: 41,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Jun',
    capitalGain: 105,
    capitalGainColor: colors.purple[900],
    dividends: 80,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Jul',
    capitalGain: 188,
    capitalGainColor: colors.purple[900],
    dividends: 100,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Aug',
    capitalGain: 215,
    capitalGainColor: colors.purple[900],
    dividends: 100,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Sep',
    capitalGain: 109,
    capitalGainColor: colors.purple[900],
    dividends: 60,
    dividendsColor: colors.blue[50],
    currencyGain: 80,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Oct',
    capitalGain: 294.35,
    capitalGainColor: colors.purple[900],
    dividends: 100,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Nov',
    capitalGain: 200,
    capitalGainColor: colors.purple[900],
    dividends: 75,
    dividendsColor: colors.blue[50],
    currencyGain: 198,
    currencyGainColor: colors.red[900],
  },
  {
    month: 'Dez',
    capitalGain: 260,
    capitalGainColor: colors.purple[900],
    dividends: 90,
    dividendsColor: colors.blue[50],
    currencyGain: 140,
    currencyGainColor: colors.red[900],
  },
];
